import type { UniverseItem, UniverseCategory } from "./universe.types";

export const universeCategories: readonly UniverseCategory[] = [
  "전체",
  "인기",
  "최신",
  "게임",
  "스포츠",
  "일상",
  "팬덤",
  "구독 중",
] as const;

export const quickTags = ["게임", "야구", "축구", "IT", "일상", "팬덤"];

export const mockUniverses: UniverseItem[] = [
  {
    id: "1",
    slug: "baseball-dugout",
    name: "Baseball Dugout",
    description: "오늘 경기부터 선수 이야기, 기록과 직관 후기까지 야구 좋아하는 사람들이 자유롭게 이야기하는 유니버스입니다.",
    category: "스포츠",
    subscribers: 12400,
    posts: 450,
    updatedAt: "2시간 전",
    isTrending: true,
    tags: ["야구", "KBO", "경기"],
  },
  {
    id: "2",
    slug: "game-lab",
    name: "Game Lab",
    description: "요즘 하는 게임, 업데이트 소식, 공략과 잡담을 함께 나누는 게임 종합 커뮤니티입니다.",
    category: "게임",
    subscribers: 8100,
    posts: 1200,
    updatedAt: "1일 전",
    isTrending: true,
    isNew: true,
    tags: ["게임", "공략", "잡담"],
  },
  {
    id: "3",
    slug: "daily-talk",
    name: "Daily Talk",
    description: "학교, 취미, 오늘 있었던 일처럼 가벼운 이야기를 편하게 나누는 일상 유니버스입니다.",
    category: "일상",
    subscribers: 5600,
    posts: 280,
    updatedAt: "3시간 전",
    tags: ["일상", "잡담", "취미"],
  },
  {
    id: "4",
    slug: "football-square",
    name: "Football Square",
    description: "국내외 축구 경기와 선수, 전술, 이적 소식을 두고 함께 이야기하는 축구 커뮤니티입니다.",
    category: "스포츠",
    subscribers: 15000,
    posts: 3400,
    updatedAt: "10분 전",
    isTrending: true,
    tags: ["축구", "경기", "이적시장"],
  },
  {
    id: "5",
    slug: "fan-zone",
    name: "Fan Zone",
    description: "좋아하는 작품과 인물, 밈과 새로운 소식을 함께 공유하고 이야기하는 팬덤 유니버스입니다.",
    category: "팬덤",
    subscribers: 22000,
    posts: 8900,
    updatedAt: "5분 전",
    isTrending: true,
    tags: ["팬덤", "밈", "소식"],
  },
  {
    id: "6",
    slug: "late-night-chat",
    name: "Late Night Chat",
    description: "늦은 밤에도 깨어 있는 사람들이 별일 없는 이야기부터 고민까지 편하게 나누는 공간입니다.",
    category: "일상",
    subscribers: 4200,
    posts: 150,
    updatedAt: "5일 전",
    isNew: true,
    tags: ["일상", "대화", "새벽"],
  },
];
