import type { UniverseItem, UniverseCategory } from "./universe.types";

export const universeCategories: readonly UniverseCategory[] = [
  "전체",
  "인기",
  "최신",
  "팬아트",
  "창작 세계관",
  "소설",
  "캐릭터",
  "구독 중",
] as const;

export const quickTags = ["판타지", "SF", "일상", "로맨스", "스릴러", "학원물"];

export const mockUniverses: UniverseItem[] = [
  {
    id: "1",
    slug: "stella-nova",
    name: "Stella Nova",
    description: "먼 미래, 인류가 성간 문명을 이룬 뒤 잊혀진 행성에서 벌어지는 기묘한 이야기들입니다. 고대 기술과 마법이 공존하는 독특한 세계관을 탐험해보세요.",
    category: "창작 세계관",
    subscribers: 12400,
    posts: 450,
    updatedAt: "2시간 전",
    isTrending: true,
    tags: ["SF", "판타지", "스페이스오페라"],
  },
  {
    id: "2",
    slug: "dream-archive",
    name: "Dream Archive",
    description: "사람들의 꿈을 수집하고 관리하는 비밀 도서관. 당신의 꿈은 어떤 책으로 기록되어 있을까요? 매일 새로운 꿈의 조각들이 업데이트됩니다.",
    category: "소설",
    subscribers: 8100,
    posts: 1200,
    updatedAt: "1일 전",
    isTrending: true,
    isNew: true,
    tags: ["판타지", "미스터리", "일상"],
  },
  {
    id: "3",
    slug: "blue-orbit",
    name: "Blue Orbit",
    description: "해저 문명이 지배하는 푸른 행성, 아쿠아리스. 지상인과 해저인의 갈등과 화해를 다룬 장편 서사시입니다.",
    category: "창작 세계관",
    subscribers: 5600,
    posts: 280,
    updatedAt: "3시간 전",
    tags: ["SF", "어드벤처", "정치"],
  },
  {
    id: "4",
    slug: "character-forge",
    name: "Character Forge",
    description: "다양한 캐릭터 설정과 일러스트를 공유하는 곳입니다. 당신만의 매력적인 캐릭터를 만들고 다른 창작자들과 교류해보세요.",
    category: "캐릭터",
    subscribers: 15000,
    posts: 3400,
    updatedAt: "10분 전",
    isTrending: true,
    tags: ["캐릭터", "디자인", "팁"],
  },
  {
    id: "5",
    slug: "fanart-central",
    name: "Fanart Central",
    description: "다양한 서브컬처 작품들의 고퀄리티 팬아트가 모이는 허브입니다. 최신 인기 애니메이션부터 고전 명작까지 모두 만나보세요.",
    category: "팬아트",
    subscribers: 22000,
    posts: 8900,
    updatedAt: "5분 전",
    isTrending: true,
    tags: ["일러스트", "팬아트", "종합"],
  },
  {
    id: "6",
    slug: "midnight-station",
    name: "Midnight Station",
    description: "자정에만 나타나는 기차역. 그곳에서 만나는 사람들의 짧지만 강렬한 이야기들. 옴니버스 형식의 단편 소설 모음집입니다.",
    category: "소설",
    subscribers: 4200,
    posts: 150,
    updatedAt: "5일 전",
    isNew: true,
    tags: ["단편", "감성", "판타지"],
  },
];
