-- Drawing Verse community persistence
-- Run this once in the Supabase SQL editor before testing persistent comments.

-- Keep the post columns used by the current UI/API consistent.
alter table public.posts
  add column if not exists author_id uuid references auth.users(id) on delete set null,
  add column if not exists author text,
  add column if not exists universe_slug text,
  add column if not exists likes_count integer not null default 0,
  add column if not exists comments_count integer not null default 0,
  add column if not exists views_count integer not null default 0,
  add column if not exists created_at timestamptz not null default now();

-- post_id is text on purpose. Existing Drawing Verse code has used both numeric
-- and string post IDs, so comparing posts.id::text keeps this migration safe for
-- either bigint-style or UUID-style post IDs.
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id text not null,
  author_id uuid not null references auth.users(id) on delete cascade,
  author text not null,
  content text not null check (char_length(content) between 1 and 3000),
  created_at timestamptz not null default now()
);

create index if not exists comments_post_id_created_at_idx
  on public.comments (post_id, created_at);

create index if not exists comments_author_id_idx
  on public.comments (author_id);

alter table public.comments enable row level security;

-- Re-create policies with deterministic names so this migration is re-runnable.
drop policy if exists "comments_read_all" on public.comments;
create policy "comments_read_all"
  on public.comments
  for select
  using (true);

drop policy if exists "comments_insert_own" on public.comments;
create policy "comments_insert_own"
  on public.comments
  for insert
  to authenticated
  with check (auth.uid() = author_id);

drop policy if exists "comments_update_own" on public.comments;
create policy "comments_update_own"
  on public.comments
  for update
  to authenticated
  using (auth.uid() = author_id)
  with check (auth.uid() = author_id);

drop policy if exists "comments_delete_own" on public.comments;
create policy "comments_delete_own"
  on public.comments
  for delete
  to authenticated
  using (auth.uid() = author_id);

-- New-post API writes author_id from the authenticated Supabase user.
alter table public.posts enable row level security;

drop policy if exists "posts_insert_own" on public.posts;
create policy "posts_insert_own"
  on public.posts
  for insert
  to authenticated
  with check (auth.uid() = author_id);

-- Keep comments_count in posts synchronized without requiring the client to
-- have permission to update arbitrary post rows.
create or replace function public.sync_post_comments_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_post_id text;
begin
  if tg_op = 'DELETE' then
    target_post_id := old.post_id;
  else
    target_post_id := new.post_id;
  end if;

  update public.posts
  set comments_count = (
    select count(*)::integer
    from public.comments
    where post_id = target_post_id
  )
  where id::text = target_post_id;

  if tg_op = 'UPDATE' and old.post_id is distinct from new.post_id then
    update public.posts
    set comments_count = (
      select count(*)::integer
      from public.comments
      where post_id = old.post_id
    )
    where id::text = old.post_id;
  end if;

  return null;
end;
$$;

drop trigger if exists comments_sync_post_count on public.comments;
create trigger comments_sync_post_count
after insert or delete or update of post_id on public.comments
for each row execute function public.sync_post_comments_count();
