-- Drawing Verse Supabase alignment
-- Prepared against the live public schema on 2026-08-25.
-- Apply this migration only after reviewing it in the target Supabase project.

-- ---------------------------------------------------------------------------
-- 1. Core columns that the current product UI needs
-- ---------------------------------------------------------------------------

alter table public.posts
  add column if not exists view_count integer not null default 0;

alter table public.universes
  add column if not exists owner_id uuid references auth.users(id) on delete set null;

create index if not exists universes_owner_id_idx
  on public.universes(owner_id);

-- ---------------------------------------------------------------------------
-- 2. Persistent post comments
-- ---------------------------------------------------------------------------

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  author text not null,
  content text not null check (char_length(content) between 1 and 3000),
  created_at timestamptz not null default now()
);

create index if not exists comments_post_id_created_at_idx
  on public.comments(post_id, created_at);
create index if not exists comments_user_id_idx
  on public.comments(user_id);

alter table public.comments enable row level security;

grant select on public.comments to anon, authenticated;
grant insert, update, delete on public.comments to authenticated;
grant usage, select on sequence public.comments_id_seq to authenticated;

drop policy if exists "comments_public_read" on public.comments;
create policy "comments_public_read"
  on public.comments for select
  to anon, authenticated
  using (true);

drop policy if exists "comments_insert_own" on public.comments;
create policy "comments_insert_own"
  on public.comments for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "comments_update_own" on public.comments;
create policy "comments_update_own"
  on public.comments for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "comments_delete_own" on public.comments;
create policy "comments_delete_own"
  on public.comments for delete
  to authenticated
  using ((select auth.uid()) = user_id);

-- Keep posts.comment_count authoritative in the database.
create or replace function public.sync_post_comment_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
begin
  target_id := case when tg_op = 'DELETE' then old.post_id else new.post_id end;

  update public.posts
  set comment_count = (
    select count(*)::integer
    from public.comments
    where post_id = target_id
  )
  where id = target_id;

  if tg_op = 'UPDATE' and old.post_id is distinct from new.post_id then
    update public.posts
    set comment_count = (
      select count(*)::integer
      from public.comments
      where post_id = old.post_id
    )
    where id = old.post_id;
  end if;

  return null;
end;
$$;

drop trigger if exists comments_sync_post_count on public.comments;
create trigger comments_sync_post_count
after insert or delete or update of post_id on public.comments
for each row execute function public.sync_post_comment_count();

-- Keep posts.like_count authoritative even when someone stars another user's post.
create or replace function public.sync_post_like_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
begin
  target_id := case when tg_op = 'DELETE' then old.post_id else new.post_id end;

  update public.posts
  set like_count = (
    select count(*)::integer
    from public.post_stars
    where post_id = target_id
  )
  where id = target_id;

  if tg_op = 'UPDATE' and old.post_id is distinct from new.post_id then
    update public.posts
    set like_count = (
      select count(*)::integer
      from public.post_stars
      where post_id = old.post_id
    )
    where id = old.post_id;
  end if;

  return null;
end;
$$;

drop trigger if exists post_stars_sync_post_count on public.post_stars;
create trigger post_stars_sync_post_count
after insert or delete or update of post_id on public.post_stars
for each row execute function public.sync_post_like_count();

-- ---------------------------------------------------------------------------
-- 3. Universe ownership and counters
-- ---------------------------------------------------------------------------

alter table public.universes enable row level security;

drop policy if exists "authenticated can create universes" on public.universes;
create policy "authenticated can create universes"
  on public.universes for insert
  to authenticated
  with check ((select auth.uid()) = owner_id);

drop policy if exists "owners can update universes" on public.universes;
create policy "owners can update universes"
  on public.universes for update
  to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

drop policy if exists "owners can delete universes" on public.universes;
create policy "owners can delete universes"
  on public.universes for delete
  to authenticated
  using ((select auth.uid()) = owner_id);

create or replace function public.sync_universe_post_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_slug text;
begin
  target_slug := case when tg_op = 'DELETE' then old.universe_slug else new.universe_slug end;

  if target_slug is not null then
    update public.universes
    set post_count = (
      select count(*)::integer from public.posts where universe_slug = target_slug
    )
    where slug = target_slug;
  end if;

  if tg_op = 'UPDATE' and old.universe_slug is distinct from new.universe_slug and old.universe_slug is not null then
    update public.universes
    set post_count = (
      select count(*)::integer from public.posts where universe_slug = old.universe_slug
    )
    where slug = old.universe_slug;
  end if;

  return null;
end;
$$;

drop trigger if exists posts_sync_universe_count on public.posts;
create trigger posts_sync_universe_count
after insert or delete or update of universe_slug on public.posts
for each row execute function public.sync_universe_post_count();

create or replace function public.sync_universe_subscriber_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_slug text;
begin
  target_slug := case when tg_op = 'DELETE' then old.universe_slug else new.universe_slug end;

  update public.universes
  set subscriber_count = (
    select count(*)::integer
    from public.universe_subscriptions
    where universe_slug = target_slug
  )
  where slug = target_slug;

  if tg_op = 'UPDATE' and old.universe_slug is distinct from new.universe_slug then
    update public.universes
    set subscriber_count = (
      select count(*)::integer
      from public.universe_subscriptions
      where universe_slug = old.universe_slug
    )
    where slug = old.universe_slug;
  end if;

  return null;
end;
$$;

drop trigger if exists subscriptions_sync_universe_count on public.universe_subscriptions;
create trigger subscriptions_sync_universe_count
after insert or delete or update of universe_slug on public.universe_subscriptions
for each row execute function public.sync_universe_subscriber_count();

create or replace function public.sync_profile_universe_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_user uuid;
begin
  target_user := case when tg_op = 'DELETE' then old.owner_id else new.owner_id end;

  if target_user is not null then
    update public.profiles
    set universes_count = (
      select count(*)::integer from public.universes where owner_id = target_user
    )
    where id = target_user;
  end if;

  if tg_op = 'UPDATE' and old.owner_id is distinct from new.owner_id and old.owner_id is not null then
    update public.profiles
    set universes_count = (
      select count(*)::integer from public.universes where owner_id = old.owner_id
    )
    where id = old.owner_id;
  end if;

  return null;
end;
$$;

drop trigger if exists universes_sync_profile_count on public.universes;
create trigger universes_sync_profile_count
after insert or delete or update of owner_id on public.universes
for each row execute function public.sync_profile_universe_count();

-- ---------------------------------------------------------------------------
-- 4. Safe view-count RPCs
-- ---------------------------------------------------------------------------

create or replace function public.increment_post_view(target_post_id bigint)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  next_count integer;
begin
  update public.posts
  set view_count = view_count + 1
  where id = target_post_id
  returning view_count into next_count;

  return coalesce(next_count, 0);
end;
$$;

grant execute on function public.increment_post_view(bigint) to anon, authenticated;

create or replace function public.increment_gallery_view(target_gallery_id bigint)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  next_count integer;
begin
  update public.gallery
  set view_count = view_count + 1
  where id = target_gallery_id
  returning view_count into next_count;

  return coalesce(next_count, 0);
end;
$$;

grant execute on function public.increment_gallery_view(bigint) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. Verse Talk persistence + atomic matching
-- ---------------------------------------------------------------------------

create table if not exists public.verse_talk_queue (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 1 and 30),
  created_at timestamptz not null default now()
);

create table if not exists public.verse_talk_rooms (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references auth.users(id) on delete cascade,
  user_b uuid not null references auth.users(id) on delete cascade,
  user_a_nickname text not null,
  user_b_nickname text not null,
  status text not null default 'active' check (status in ('active', 'ended')),
  created_at timestamptz not null default now(),
  ended_at timestamptz,
  check (user_a <> user_b)
);

create index if not exists verse_talk_rooms_user_a_idx on public.verse_talk_rooms(user_a, created_at desc);
create index if not exists verse_talk_rooms_user_b_idx on public.verse_talk_rooms(user_b, created_at desc);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.verse_talk_rooms(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists messages_room_created_at_idx on public.messages(room_id, created_at);

alter table public.verse_talk_queue enable row level security;
alter table public.verse_talk_rooms enable row level security;
alter table public.messages enable row level security;

grant select, insert, update, delete on public.verse_talk_queue to authenticated;
grant select, update on public.verse_talk_rooms to authenticated;
grant select, insert on public.messages to authenticated;

drop policy if exists "queue_read_own" on public.verse_talk_queue;
create policy "queue_read_own"
  on public.verse_talk_queue for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "queue_insert_own" on public.verse_talk_queue;
create policy "queue_insert_own"
  on public.verse_talk_queue for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "queue_update_own" on public.verse_talk_queue;
create policy "queue_update_own"
  on public.verse_talk_queue for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "queue_delete_own" on public.verse_talk_queue;
create policy "queue_delete_own"
  on public.verse_talk_queue for delete
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "room_participants_read" on public.verse_talk_rooms;
create policy "room_participants_read"
  on public.verse_talk_rooms for select
  to authenticated
  using ((select auth.uid()) in (user_a, user_b));

drop policy if exists "room_participants_update" on public.verse_talk_rooms;
create policy "room_participants_update"
  on public.verse_talk_rooms for update
  to authenticated
  using ((select auth.uid()) in (user_a, user_b))
  with check ((select auth.uid()) in (user_a, user_b));

drop policy if exists "messages_participants_read" on public.messages;
create policy "messages_participants_read"
  on public.messages for select
  to authenticated
  using (
    exists (
      select 1
      from public.verse_talk_rooms r
      where r.id = room_id
        and (select auth.uid()) in (r.user_a, r.user_b)
    )
  );

drop policy if exists "messages_participants_insert" on public.messages;
create policy "messages_participants_insert"
  on public.messages for insert
  to authenticated
  with check (
    (select auth.uid()) = sender_id
    and exists (
      select 1
      from public.verse_talk_rooms r
      where r.id = room_id
        and r.status = 'active'
        and (select auth.uid()) in (r.user_a, r.user_b)
    )
  );

create or replace function public.match_verse_talk(display_nickname text)
returns setof public.verse_talk_rooms
language plpgsql
security definer
set search_path = ''
as $$
declare
  me uuid := auth.uid();
  clean_nickname text := left(trim(display_nickname), 30);
  opponent public.verse_talk_queue%rowtype;
  existing_room public.verse_talk_rooms%rowtype;
  created_room public.verse_talk_rooms%rowtype;
begin
  if me is null then
    raise exception 'authentication required';
  end if;

  if clean_nickname is null or clean_nickname = '' then
    raise exception 'nickname required';
  end if;

  select * into existing_room
  from public.verse_talk_rooms
  where status = 'active' and (user_a = me or user_b = me)
  order by created_at desc
  limit 1;

  if found then
    return next existing_room;
    return;
  end if;

  delete from public.verse_talk_queue where user_id = me;

  select * into opponent
  from public.verse_talk_queue
  where user_id <> me
  order by created_at asc
  for update skip locked
  limit 1;

  if found then
    delete from public.verse_talk_queue where id = opponent.id;

    insert into public.verse_talk_rooms(
      user_a, user_b, user_a_nickname, user_b_nickname, status
    ) values (
      me, opponent.user_id, clean_nickname, opponent.nickname, 'active'
    )
    returning * into created_room;

    return next created_room;
    return;
  end if;

  insert into public.verse_talk_queue(user_id, nickname)
  values (me, clean_nickname)
  on conflict (user_id)
  do update set nickname = excluded.nickname, created_at = now();

  return;
end;
$$;

grant execute on function public.match_verse_talk(text) to authenticated;

-- ---------------------------------------------------------------------------
-- 6. Gallery Storage
-- ---------------------------------------------------------------------------

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'gallery',
  'gallery',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "gallery_storage_upload_own" on storage.objects;
create policy "gallery_storage_upload_own"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'gallery'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "gallery_storage_update_own" on storage.objects;
create policy "gallery_storage_update_own"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'gallery'
    and owner_id = (select auth.uid())::text
  )
  with check (
    bucket_id = 'gallery'
    and owner_id = (select auth.uid())::text
  );

drop policy if exists "gallery_storage_delete_own" on storage.objects;
create policy "gallery_storage_delete_own"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'gallery'
    and owner_id = (select auth.uid())::text
  );

-- ---------------------------------------------------------------------------
-- 7. Realtime tables used by the current UI
-- ---------------------------------------------------------------------------

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'posts'
  ) then
    alter publication supabase_realtime add table public.posts;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'universes'
  ) then
    alter publication supabase_realtime add table public.universes;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'verse_talk_rooms'
  ) then
    alter publication supabase_realtime add table public.verse_talk_rooms;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 8. Counter backfills
-- ---------------------------------------------------------------------------

update public.posts p
set comment_count = (
  select count(*)::integer from public.comments c where c.post_id = p.id
);

update public.posts p
set like_count = (
  select count(*)::integer from public.post_stars s where s.post_id = p.id
);

update public.universes u
set post_count = (
  select count(*)::integer from public.posts p where p.universe_slug = u.slug
),
subscriber_count = (
  select count(*)::integer from public.universe_subscriptions s where s.universe_slug = u.slug
);

update public.profiles p
set universes_count = (
  select count(*)::integer from public.universes u where u.owner_id = p.id
);
