-- Drawing Verse: Stellar Systems
-- Hierarchy: Galaxy -> Universe -> Stellar System -> content

create table public.stellar_systems (
  id bigint generated by default as identity primary key,
  universe_slug text not null references public.universes(slug) on update cascade on delete cascade,
  slug text not null,
  name text not null,
  description text not null default '',
  icon text not null default '☀️',
  accent text not null default '#f59e0b',
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stellar_system_slug_format check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(slug) <= 64),
  constraint stellar_system_name_length check (char_length(btrim(name)) between 1 and 60),
  constraint stellar_system_description_length check (char_length(description) <= 280),
  constraint stellar_system_icon_length check (char_length(icon) <= 16),
  constraint stellar_system_accent_format check (accent ~ '^#[0-9A-Fa-f]{6}$'),
  unique (universe_slug, slug)
);

create index stellar_systems_universe_slug_idx on public.stellar_systems (universe_slug);
create index stellar_systems_owner_id_idx on public.stellar_systems (owner_id);
create index stellar_systems_created_at_idx on public.stellar_systems (created_at desc);

alter table public.stellar_systems enable row level security;

grant select on public.stellar_systems to anon, authenticated;
grant insert, update, delete on public.stellar_systems to authenticated;
grant usage, select on sequence public.stellar_systems_id_seq to authenticated;

create policy stellar_systems_select on public.stellar_systems
  for select to anon, authenticated
  using (
    exists (
      select 1 from public.universes u
      where u.slug = stellar_systems.universe_slug
        and (u.visibility = 'public' or u.owner_id = (select auth.uid()))
    )
  );

create policy stellar_systems_insert on public.stellar_systems
  for insert to authenticated
  with check (
    owner_id = (select auth.uid())
    and exists (
      select 1 from public.universes u
      where u.slug = stellar_systems.universe_slug
        and u.owner_id = (select auth.uid())
    )
  );

create policy stellar_systems_update on public.stellar_systems
  for update to authenticated
  using (
    owner_id = (select auth.uid())
    and exists (
      select 1 from public.universes u
      where u.slug = stellar_systems.universe_slug
        and u.owner_id = (select auth.uid())
    )
  )
  with check (
    owner_id = (select auth.uid())
    and exists (
      select 1 from public.universes u
      where u.slug = stellar_systems.universe_slug
        and u.owner_id = (select auth.uid())
    )
  );

create policy stellar_systems_delete on public.stellar_systems
  for delete to authenticated
  using (
    owner_id = (select auth.uid())
    and exists (
      select 1 from public.universes u
      where u.slug = stellar_systems.universe_slug
        and u.owner_id = (select auth.uid())
    )
  );
