create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  display_name text,
  avatar_url text,
  bio text,
  about text,
  tags text[] not null default '{}',
  followers_count integer not null default 0 check (followers_count >= 0),
  posts_count integer not null default 0 check (posts_count >= 0),
  artworks_count integer not null default 0 check (artworks_count >= 0),
  universes_count integer not null default 0 check (universes_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "profiles_public_read" on public.profiles;
create policy "profiles_public_read"
on public.profiles for select
to anon, authenticated
using (true);

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  fallback_nickname text;
begin
  fallback_nickname := 'creator_' || substr(replace(new.id::text, '-', ''), 1, 8);

  insert into public.profiles (
    id,
    nickname,
    display_name,
    avatar_url,
    created_at,
    updated_at
  ) values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'nickname'), ''),
      nullif(trim(new.raw_user_meta_data ->> 'user_name'), ''),
      fallback_nickname
    ),
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''),
      nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''),
      nullif(trim(new.raw_user_meta_data ->> 'name'), ''),
      nullif(trim(new.raw_user_meta_data ->> 'nickname'), ''),
      fallback_nickname
    ),
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'avatar_url'), ''),
      nullif(trim(new.raw_user_meta_data ->> 'picture'), '')
    ),
    coalesce(new.created_at, now()),
    now()
  )
  on conflict (id) do update set
    nickname = coalesce(excluded.nickname, public.profiles.nickname),
    display_name = coalesce(excluded.display_name, public.profiles.display_name),
    avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
after insert on auth.users
for each row execute function public.handle_new_user_profile();

insert into public.profiles (id, nickname, display_name, avatar_url, created_at)
select
  u.id,
  coalesce(
    nullif(trim(u.raw_user_meta_data ->> 'nickname'), ''),
    nullif(trim(u.raw_user_meta_data ->> 'user_name'), ''),
    'creator_' || substr(replace(u.id::text, '-', ''), 1, 8)
  ),
  coalesce(
    nullif(trim(u.raw_user_meta_data ->> 'display_name'), ''),
    nullif(trim(u.raw_user_meta_data ->> 'full_name'), ''),
    nullif(trim(u.raw_user_meta_data ->> 'name'), ''),
    nullif(trim(u.raw_user_meta_data ->> 'nickname'), ''),
    'creator_' || substr(replace(u.id::text, '-', ''), 1, 8)
  ),
  coalesce(
    nullif(trim(u.raw_user_meta_data ->> 'avatar_url'), ''),
    nullif(trim(u.raw_user_meta_data ->> 'picture'), '')
  ),
  u.created_at
from auth.users u
on conflict (id) do nothing;

create table if not exists public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint follows_not_self check (follower_id <> following_id),
  constraint follows_unique_pair unique (follower_id, following_id)
);

create index if not exists follows_following_id_idx on public.follows(following_id);
create index if not exists follows_follower_id_idx on public.follows(follower_id);

alter table public.follows enable row level security;

drop policy if exists "follows_public_read" on public.follows;
create policy "follows_public_read"
on public.follows for select
to anon, authenticated
using (true);

drop policy if exists "follows_insert_self" on public.follows;
create policy "follows_insert_self"
on public.follows for insert
to authenticated
with check (auth.uid() = follower_id);

drop policy if exists "follows_delete_self" on public.follows;
create policy "follows_delete_self"
on public.follows for delete
to authenticated
using (auth.uid() = follower_id);

create or replace function public.refresh_followers_count(target_user uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.profiles p
  set followers_count = (
    select count(*)::int
    from public.follows f
    where f.following_id = target_user
  )
  where p.id = target_user;
$$;

create or replace function public.sync_followers_count_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.refresh_followers_count(old.following_id);
    return old;
  end if;

  perform public.refresh_followers_count(new.following_id);
  return new;
end;
$$;

drop trigger if exists follows_sync_count on public.follows;
create trigger follows_sync_count
after insert or delete on public.follows
for each row execute function public.sync_followers_count_trigger();

create or replace function public.refresh_profile_content_counts(target_user uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if target_user is null then
    return;
  end if;

  update public.profiles p
  set
    posts_count = (select count(*)::int from public.posts po where po.user_id = target_user),
    artworks_count = (select count(*)::int from public.gallery ga where ga.user_id = target_user)
  where p.id = target_user;
end;
$$;

create or replace function public.sync_profile_content_counts_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.refresh_profile_content_counts(old.user_id);
    return old;
  elsif tg_op = 'UPDATE' then
    if old.user_id is distinct from new.user_id then
      perform public.refresh_profile_content_counts(old.user_id);
    end if;
    perform public.refresh_profile_content_counts(new.user_id);
    return new;
  else
    perform public.refresh_profile_content_counts(new.user_id);
    return new;
  end if;
end;
$$;

drop trigger if exists posts_sync_profile_count on public.posts;
create trigger posts_sync_profile_count
after insert or delete or update of user_id on public.posts
for each row execute function public.sync_profile_content_counts_trigger();

drop trigger if exists gallery_sync_profile_count on public.gallery;
create trigger gallery_sync_profile_count
after insert or delete or update of user_id on public.gallery
for each row execute function public.sync_profile_content_counts_trigger();

create or replace function public.get_monthly_creators(limit_count integer default 3)
returns table (
  id uuid,
  nickname text,
  display_name text,
  avatar_url text,
  followers_count integer,
  tags text[],
  artworks_count bigint,
  monthly_score numeric
)
language sql
stable
security invoker
set search_path = public
as $$
  with monthly as (
    select
      g.user_id,
      count(*) as artworks_count,
      coalesce(sum(g.like_count), 0) as likes,
      coalesce(sum(g.comment_count), 0) as comments,
      coalesce(sum(g.view_count), 0) as views,
      coalesce(
        array_agg(distinct g.category) filter (where g.category is not null and trim(g.category) <> ''),
        '{}'::text[]
      ) as tags
    from public.gallery g
    where g.user_id is not null
      and g.created_at >= date_trunc('month', now())
      and g.created_at < date_trunc('month', now()) + interval '1 month'
    group by g.user_id
  )
  select
    p.id,
    p.nickname,
    p.display_name,
    p.avatar_url,
    p.followers_count,
    m.tags,
    m.artworks_count,
    round(
      m.artworks_count * 20
      + m.likes * 4
      + m.comments * 6
      + m.views * 0.1
      + p.followers_count * 0.5,
      1
    ) as monthly_score
  from monthly m
  join public.profiles p on p.id = m.user_id
  order by monthly_score desc, p.followers_count desc, p.created_at asc
  limit greatest(1, least(coalesce(limit_count, 3), 12));
$$;

revoke all on function public.get_monthly_creators(integer) from public;
grant execute on function public.get_monthly_creators(integer) to anon, authenticated;

select public.refresh_profile_content_counts(p.id) from public.profiles p;
select public.refresh_followers_count(p.id) from public.profiles p;
