create table public.galaxies (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.galaxies enable row level security;
grant select on table public.galaxies to anon, authenticated;

create policy "public can read galaxies"
on public.galaxies
for select
to anon, authenticated
using (true);

alter table public.universes
  add column galaxy_id bigint references public.galaxies(id) on delete set null,
  add column tags text[] not null default '{}';

create index universes_galaxy_id_idx on public.universes(galaxy_id);

insert into public.galaxies (slug, name, description)
values (
  'sports',
  '스포츠 은하',
  '경기와 선수, 팀과 팬들의 이야기가 모이는 스포츠 세계입니다.'
);

insert into public.universes (
  slug,
  name,
  description,
  category,
  subscriber_count,
  post_count,
  tags,
  galaxy_id
)
select
  'baseball',
  '야구 유니버스',
  'KBO부터 MLB까지, 경기 이야기와 응원 열기를 함께 나누는 야구 팬들의 공간입니다.',
  '인기',
  0,
  0,
  array['KBO', 'MLB', '한화 이글스']::text[],
  galaxies.id
from public.galaxies
where galaxies.slug = 'sports';
